import { Movie } from '../types';

export const MOVIE_DATABASE: Movie[] = [
  {
    id: "interstellar",
    title: "Interstellar",
    year: 2014,
    director: ["Christopher Nolan"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    genres: ["Sci-Fi", "Drama", "Adventure"],
    poster: "🚀",
    rating: 8.7,
    runtime: 169,
    description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    awards: "Won 1 Oscar. 44 wins & 148 nominations total.",
    tropes: ["Time Dilation", "Dying Earth", "Space Exploration", "Father-Daughter Bond", "Cerebral Plot", "Hans Zimmer Score", "Tear-Jerker Ending"],
    boxOffice: "$773.8 Million",
    rottenTomatoes: 73,
    metacritic: 74,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 4, complexity: 9, visuals: 10, emotion: 9 }
  },
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    director: ["Christopher Nolan"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Cillian Murphy"],
    genres: ["Sci-Fi", "Action", "Adventure"],
    poster: "🌀",
    rating: 8.8,
    runtime: 148,
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    awards: "Won 4 Oscars. 159 wins & 220 nominations total.",
    tropes: ["Heist", "Dream Within a Dream", "Mind-bending", "Unreliable Narrator", "Dead Wife Flashbacks", "Architectural Folding", "Ambiguous Ending"],
    boxOffice: "$839.0 Million",
    rottenTomatoes: 87,
    metacritic: 74,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 4, complexity: 9, visuals: 9, emotion: 6 }
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    year: 2008,
    director: ["Christopher Nolan"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal", "Gary Oldman"],
    genres: ["Action", "Crime", "Drama", "Thriller"],
    poster: "🦇",
    rating: 9.0,
    runtime: 152,
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    awards: "Won 2 Oscars. 163 wins & 164 nominations total.",
    tropes: ["Chaos Agent", "Tragic Fall from Grace", "Moral Dilemma", "Vigilante Justice", "Gritty Realism", "Collateral Damage", "Iconic Villain"],
    boxOffice: "$1.006 Billion",
    rottenTomatoes: 94,
    metacritic: 84,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 2, complexity: 7, visuals: 8, emotion: 7 }
  },
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    year: 2024,
    director: ["Denis Villeneuve"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Austin Butler", "Florence Pugh"],
    genres: ["Sci-Fi", "Adventure", "Drama"],
    poster: "🏜️",
    rating: 8.6,
    runtime: 166,
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future only he can foresee.",
    awards: "Highly acclaimed. Anticipated major awards contender.",
    tropes: ["Messiah Complex", "Desert Warfare", "Giant Monsters", "Political Intrigue", "Betrayal", "Religious Fanaticism", "Epic Scale", "Sci-Fi Lore"],
    boxOffice: "$711.8 Million",
    rottenTomatoes: 92,
    metacritic: 79,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 3, complexity: 8, visuals: 10, emotion: 8 }
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    director: ["George Miller"],
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
    genres: ["Action", "Adventure", "Sci-Fi"],
    poster: "🔥",
    rating: 8.1,
    runtime: 120,
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    awards: "Won 6 Oscars. 248 wins & 232 nominations total.",
    tropes: ["Post-Apocalyptic", "High-Octane Chase", "Practical Effects", "Silent Protagonist", "Feminist Undertones", "Dystopian Society", "Flamethrower Guitar"],
    boxOffice: "$380.4 Million",
    rottenTomatoes: 97,
    metacritic: 90,
    mpaaRating: "R",
    attributes: { pacing: 10, tone: 3, complexity: 4, visuals: 10, emotion: 6 }
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    director: ["Damien Chazelle"],
    cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
    genres: ["Romance", "Drama", "Comedy", "Music"],
    poster: "💃",
    rating: 8.0,
    runtime: 128,
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    awards: "Won 6 Oscars. 243 wins & 297 nominations total.",
    tropes: ["Musical Numbers", "Star-Crossed Lovers", "Hollywood Dreams", "Jazz Nostalgia", "Bittersweet Ending", "Vibrant Color Palette", "Season-Based Narrative"],
    boxOffice: "$448.9 Million",
    rottenTomatoes: 91,
    metacritic: 94,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 7, complexity: 5, visuals: 8, emotion: 9 }
  },
  {
    id: "whiplash",
    title: "Whiplash",
    year: 2014,
    director: ["Damien Chazelle"],
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
    genres: ["Drama", "Music"],
    poster: "🥁",
    rating: 8.5,
    runtime: 106,
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    awards: "Won 3 Oscars. 96 wins & 144 nominations total.",
    tropes: ["Abusive Mentor", "Obsession with Greatness", "Blood, Sweat & Tears", "High-Stakes Performance", "Psychological Warfare", "Frenetic Editing", "Jazz Music"],
    boxOffice: "$49.0 Million",
    rottenTomatoes: 94,
    metacritic: 89,
    mpaaRating: "R",
    attributes: { pacing: 9, tone: 3, complexity: 6, visuals: 6, emotion: 8 }
  },
  {
    id: "everything-everywhere",
    title: "Everything Everywhere All At Once",
    year: 2022,
    director: ["Daniel Kwan", "Daniel Scheinert"],
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "James Hong", "Jamie Lee Curtis"],
    genres: ["Sci-Fi", "Action", "Comedy", "Drama", "Fantasy"],
    poster: "🥯",
    rating: 8.1,
    runtime: 139,
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save the world by exploring other universes connecting with the lives she could have led.",
    awards: "Won 7 Oscars. 407 wins & 371 nominations total.",
    tropes: ["Multiverse", "Generational Trauma", "Absurdist Humor", "Martial Arts", "Nihilism vs Optimism", "Googly Eyes", "Hot Dog Fingers", "Mother-Daughter Bond"],
    boxOffice: "$143.4 Million",
    rottenTomatoes: 93,
    metacritic: 81,
    mpaaRating: "R",
    attributes: { pacing: 9, tone: 6, complexity: 9, visuals: 9, emotion: 9 }
  },
  {
    id: "parasite",
    title: "Parasite",
    year: 2019,
    director: ["Bong Joon Ho"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
    genres: ["Thriller", "Drama", "Comedy", "Crime"],
    poster: "🏠",
    rating: 8.5,
    runtime: 132,
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    awards: "Won 4 Oscars (First Foreign Language Best Picture). 308 wins total.",
    tropes: ["Class Struggle", "Genre-Fluid", "Home Invasion", "Dark Secrets", "Metaphorical Rocks", "Con Artists", "Shocking Plot Twist", "Tragic Downfall"],
    boxOffice: "$262.7 Million",
    rottenTomatoes: 99,
    metacritic: 96,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 3, complexity: 8, visuals: 7, emotion: 7 }
  },
  {
    id: "hereditary",
    title: "Hereditary",
    year: 2018,
    director: ["Ari Aster"],
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Ann Dowd", "Gabriel Byrne"],
    genres: ["Horror", "Drama", "Mystery"],
    poster: "👑",
    rating: 7.3,
    runtime: 127,
    description: "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
    awards: "48 wins & 111 nominations total.",
    tropes: ["Cult Secret Society", "Generational Curse", "Grief and Trauma", "Demonic Possession", "Shocking Death", "Slow-Burn Dread", "Disturbing Imagery", "Jumpscare Free (Mostly)"],
    boxOffice: "$82.8 Million",
    rottenTomatoes: 90,
    metacritic: 87,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 1, complexity: 8, visuals: 6, emotion: 8 }
  },
  {
    id: "get-out",
    title: "Get Out",
    year: 2017,
    director: ["Jordan Peele"],
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener", "Lil Rel Howery"],
    genres: ["Horror", "Thriller", "Mystery"],
    poster: "☕",
    rating: 7.8,
    runtime: 104,
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him reaches a boiling point.",
    awards: "Won 1 Oscar. 154 wins & 207 nominations total.",
    tropes: ["Social Satire", "Mind Control", "Microaggressions", "The 'Sunken Place'", "Creepy Suburbia", "Conspiracy", "Cathartic Ending", "Hypnosis"],
    boxOffice: "$255.4 Million",
    rottenTomatoes: 98,
    metacritic: 85,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 3, complexity: 7, visuals: 6, emotion: 6 }
  },
  {
    id: "the-notebook",
    title: "The Notebook",
    year: 2004,
    director: ["Nick Cassavetes"],
    cast: ["Ryan Gosling", "Rachel McAdams", "Gena Rowlands", "James Garner"],
    genres: ["Romance", "Drama"],
    poster: "📖",
    rating: 7.8,
    runtime: 123,
    description: "An elderly man reads to a fellow nursing home patient, who has Alzheimer's disease, the story of two young lovers from different social classes in the 1940s.",
    awards: "12 wins & 11 nominations total.",
    tropes: ["Class Difference", "First Love", "Alzheimer's / Old Age", "Summer Romance", "Rain Kiss", "Unsent Letters", "Tear-Jerker", "Flashback Narrative"],
    boxOffice: "$118.2 Million",
    rottenTomatoes: 53,
    metacritic: 53,
    mpaaRating: "PG-13",
    attributes: { pacing: 5, tone: 7, complexity: 3, visuals: 6, emotion: 10 }
  },
  {
    id: "about-time",
    title: "About Time",
    year: 2013,
    director: ["Richard Curtis"],
    cast: ["Domhnall Gleeson", "Rachel McAdams", "Bill Nighy", "Margot Robbie"],
    genres: ["Romance", "Comedy", "Drama", "Fantasy"],
    poster: "⏳",
    rating: 7.8,
    runtime: 123,
    description: "At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you would think.",
    awards: "4 wins & 12 nominations.",
    tropes: ["Time Travel", "Father-Son Bond", "British Charm", "Appreciating the Ordinary", "Meet-Cute", "Butterflies and Crying", "Life Lessons"],
    boxOffice: "$87.1 Million",
    rottenTomatoes: 70,
    metacritic: 55,
    mpaaRating: "R",
    attributes: { pacing: 6, tone: 8, complexity: 5, visuals: 5, emotion: 9 }
  },
  {
    id: "john-wick",
    title: "John Wick",
    year: 2014,
    director: ["Chad Stahelski"],
    cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
    genres: ["Action", "Thriller", "Crime"],
    poster: "🐶",
    rating: 7.4,
    runtime: 101,
    description: "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and stole his car, unleashing a fury of gun-fu choreography.",
    awards: "5 wins & 10 nominations.",
    tropes: ["Retired Badass", "Avenging a Pet", "Gun-Fu", "Underground Assassin Society", "One-Man Army", "Criminal Underworld Lore", "Neon Lighting", "Short & Punchy"],
    boxOffice: "$86.1 Million",
    rottenTomatoes: 86,
    metacritic: 68,
    mpaaRating: "R",
    attributes: { pacing: 9, tone: 3, complexity: 3, visuals: 8, emotion: 5 }
  },
  {
    id: "superbad",
    title: "Superbad",
    year: 2007,
    director: ["Greg Mottola"],
    cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse", "Bill Hader", "Seth Rogen"],
    genres: ["Comedy"],
    poster: "🍺",
    rating: 7.6,
    runtime: 113,
    description: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry, sending them on an anarchic night.",
    awards: "12 wins & 23 nominations.",
    tropes: ["Coming of Age", "High School Party", "Bromance", "McLovin / Fake ID", "Bungling Cops", "Crude Humor", "One Crazy Night", "Separation Anxiety"],
    boxOffice: "$170.8 Million",
    rottenTomatoes: 88,
    metacritic: 76,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 8, complexity: 2, visuals: 4, emotion: 6 }
  },
  {
    id: "the-shawshank-redemption",
    title: "The Shawshank Redemption",
    year: 1994,
    director: ["Frank Darabont"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    genres: ["Drama"],
    poster: "🏦",
    rating: 9.3,
    runtime: 142,
    description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion in a brutal prison.",
    awards: "Nominated for 7 Oscars. 21 wins & 43 nominations.",
    tropes: ["Prison Life", "Unjust Conviction", "Lifelong Friendship", "Corrupt Warden", "Patience & Planning", "Voiceover Narration", "Triumphant Escape", "Hope vs Despair"],
    boxOffice: "$28.8 Million",
    rottenTomatoes: 91,
    metacritic: 82,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 4, complexity: 5, visuals: 6, emotion: 9 }
  },
  {
    id: "pulp-fiction",
    title: "Pulp Fiction",
    year: 1994,
    director: ["Quentin Tarantino"],
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis", "Ving Rhames"],
    genres: ["Crime", "Drama"],
    poster: "🍔",
    rating: 8.9,
    runtime: 154,
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    awards: "Won 1 Oscar. 73 wins & 74 nominations.",
    tropes: ["Non-Linear Narrative", "Witty Dialogue", "Pop-Culture References", "Stylized Violence", "Cool Hitmen", "MacGuffin Briefcase", "Diner Hold-up", "Ensemble Cast"],
    boxOffice: "$213.9 Million",
    rottenTomatoes: 92,
    metacritic: 95,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 4, complexity: 7, visuals: 7, emotion: 4 }
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    year: 1999,
    director: ["Lana Wachowski", "Lilly Wachowski"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    genres: ["Sci-Fi", "Action"],
    poster: "🕶️",
    rating: 8.7,
    runtime: 136,
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    awards: "Won 4 Oscars. 51 wins & 51 nominations.",
    tropes: ["Simulated Reality", "The Chosen One", "Bullet Time", "Leather & Sunglasses", "Kung Fu", "Cyberpunk", "Philosophical Allegory", "Robot Overlords"],
    boxOffice: "$467.2 Million",
    rottenTomatoes: 83,
    metacritic: 73,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 3, complexity: 8, visuals: 9, emotion: 5 }
  },
  {
    id: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    director: ["Martin Scorsese"],
    cast: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley", "Michelle Williams", "Max von Sydow"],
    genres: ["Mystery", "Thriller", "Drama"],
    poster: "🏝️",
    rating: 8.2,
    runtime: 138,
    description: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane on a remote island.",
    awards: "11 wins & 64 nominations.",
    tropes: ["Unreliable Narrator", "Asylum/Mental Hospital", "Gothic Atmosphere", "Paranoia & Conspiracy", "Dead Wife Hallucinations", "Massive Plot Twist", "Tragic Ending", "Stormbound Isolated Setting"],
    boxOffice: "$294.8 Million",
    rottenTomatoes: 68,
    metacritic: 63,
    mpaaRating: "R",
    attributes: { pacing: 6, tone: 2, complexity: 8, visuals: 7, emotion: 7 }
  },
  {
    id: "the-shining",
    title: "The Shining",
    year: 1980,
    director: ["Stanley Kubrick"],
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    genres: ["Horror", "Drama"],
    poster: "🪓",
    rating: 8.4,
    runtime: 146,
    description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
    awards: "5 wins & 10 nominations.",
    tropes: ["Cabin Fever", "Haunted Hotel", "Psychological Descent", "Psychic Abilities / The Shine", "Creepy Twins", "Slow-Burn Horror", "Unexplained Phantasmagoria", "Ambiguous Narrative"],
    boxOffice: "$47.3 Million",
    rottenTomatoes: 83,
    metacritic: 66,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 1, complexity: 8, visuals: 8, emotion: 4 }
  },
  {
    id: "forrest-gump",
    title: "Forrest Gump",
    year: 1994,
    director: ["Robert Zemeckis"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    genres: ["Drama", "Romance", "Comedy"],
    poster: "🍫",
    rating: 8.8,
    runtime: 142,
    description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    awards: "Won 6 Oscars. 51 wins & 74 nominations.",
    tropes: ["Pure-Hearted Protagonist", "Historical Revisionism", "Epic Life Journey", "Unrequited Love", "Vietnam War", "Disability Representation", "Tragic Loss", "Iconic Quotes"],
    boxOffice: "$678.2 Million",
    rottenTomatoes: 71,
    metacritic: 82,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 7, complexity: 4, visuals: 6, emotion: 10 }
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    year: 2001,
    director: ["Hayao Miyazaki"],
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    genres: ["Animation", "Adventure", "Family", "Fantasy"],
    poster: "🐉",
    rating: 8.6,
    runtime: 125,
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    awards: "Won 1 Oscar (First Anime Best Animated Feature). 59 wins & 31 nominations.",
    tropes: ["Magical Realism", "Spirit World", "Coming of Age", "Bizarre Creatures", "Witches & Curses", "Environmental Themes", "Whimsical Atmosphere", "Ghibli Magic"],
    boxOffice: "$355.7 Million",
    rottenTomatoes: 96,
    metacritic: 96,
    mpaaRating: "PG",
    attributes: { pacing: 6, tone: 7, complexity: 6, visuals: 10, emotion: 8 }
  },
  {
    id: "spider-man-spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    director: ["Bob Persichetti", "Peter Ramsey", "Rodney Rothman"],
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    poster: "🕷️",
    rating: 8.4,
    runtime: 117,
    description: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    awards: "Won 1 Oscar. 84 wins & 54 nominations.",
    tropes: ["Superhero Origin", "Multiverse / Alt-Dimensions", "Groundbreaking Animation Style", "Comic Book Aesthetic", "Coming of Age", "Found Family", "Amazing Soundtrack", "Grief and Motivation"],
    boxOffice: "$384.3 Million",
    rottenTomatoes: 97,
    metacritic: 87,
    mpaaRating: "PG",
    attributes: { pacing: 9, tone: 7, complexity: 5, visuals: 10, emotion: 8 }
  },
  {
    id: "barbie",
    title: "Barbie",
    year: 2023,
    director: ["Greta Gerwig"],
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Kate McKinnon", "Will Ferrell"],
    genres: ["Comedy", "Fantasy", "Adventure"],
    poster: "🎀",
    rating: 6.9,
    runtime: 114,
    description: "Stereotypical Barbie experiences a full-on existential crisis and must travel to the real world to find herself, accompanied by an eager but confused Ken.",
    awards: "Won 1 Oscar. 182 wins & 400+ nominations.",
    tropes: ["Meta-Humor", "Feminist Commentary", "Existential Crisis", "Matriarchy vs Patriarchy", "Musical Breakout", "Neon Pink Aesthetic", "Toy Lore", "Fish out of Water"],
    boxOffice: "$1.446 Billion",
    rottenTomatoes: 88,
    metacritic: 80,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 8, complexity: 6, visuals: 9, emotion: 7 }
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    year: 2023,
    director: ["Christopher Nolan"],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
    genres: ["Biography", "Drama", "History"],
    poster: "☢️",
    rating: 8.3,
    runtime: 180,
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb, and the subsequent political fallout and security hearings.",
    awards: "Won 7 Oscars including Best Picture. 300+ wins.",
    tropes: ["Historical Biopic", "Scientific Discovery", "Moral Burden", "Political Witch-hunt", "Non-Linear Timelines", "Epic Score / Sound Design", "Black and White vs Color", "Existential Dread"],
    boxOffice: "$957.8 Million",
    rottenTomatoes: 93,
    metacritic: 90,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 2, complexity: 8, visuals: 8, emotion: 7 }
  },
  {
    id: "the-lord-of-the-rings-fellowship",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    director: ["Peter Jackson"],
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Orlando Bloom"],
    genres: ["Fantasy", "Adventure", "Action"],
    poster: "💍",
    rating: 8.9,
    runtime: 178,
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    awards: "Won 4 Oscars. 122 wins & 126 nominations.",
    tropes: ["Epic High Fantasy", "The Quest", "Found Family", "Chosen One", "Corrupting Relic", "Lore & Worldbuilding", "Ancient Evil", "Breathtaking Scenery"],
    boxOffice: "$898.2 Million",
    rottenTomatoes: 91,
    metacritic: 92,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 4, complexity: 6, visuals: 9, emotion: 8 }
  },
  {
    id: "toy-story",
    title: "Toy Story",
    year: 1995,
    director: ["John Lasseter"],
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"],
    genres: ["Animation", "Adventure", "Comedy", "Family"],
    poster: "🤠",
    rating: 8.3,
    runtime: 81,
    description: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
    awards: "Won 3 Special Oscars. 28 wins & 17 nominations.",
    tropes: ["Living Toys", "Rivalry to Bromance", "Existential Crisis", "Kidnap & Rescue", "Groundbreaking CGI", "Childhood Nostalgia", "Odd Couple"],
    boxOffice: "$394.4 Million",
    rottenTomatoes: 100,
    metacritic: 96,
    mpaaRating: "G",
    attributes: { pacing: 8, tone: 8, complexity: 3, visuals: 5, emotion: 7 }
  },
  {
    id: "se7en",
    title: "Se7en",
    year: 1995,
    director: ["David Fincher"],
    cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    poster: "📦",
    rating: 8.6,
    runtime: 127,
    description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    awards: "Nominated for 1 Oscar. 29 wins & 21 nominations.",
    tropes: ["Serial Killer", "Seven Deadly Sins", "Rainy/Grungy City", "Rookie & Veteran Duo", "Shocking Final Act", "Bleak Worldview", "Twisted Mastermind", "Box Delivery"],
    boxOffice: "$327.3 Million",
    rottenTomatoes: 83,
    metacritic: 65,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 1, complexity: 6, visuals: 7, emotion: 5 }
  },
  {
    id: "fight-club",
    title: "Fight Club",
    year: 1999,
    director: ["David Fincher"],
    cast: ["Brad Pitt", "Edward Norton", "Meat Loaf", "Zach Grenier", "Helena Bonham Carter"],
    genres: ["Drama"],
    poster: "🧼",
    rating: 8.8,
    runtime: 139,
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    awards: "Nominated for 1 Oscar. 11 wins & 15 nominations.",
    tropes: ["Unreliable Narrator", "Alter Ego", "Anti-Consumerism", "Toxic Masculinity", "Mind-bending Twist", "Gothic/Grungy Visuals", "Underground Movement", "Anarchy"],
    boxOffice: "$101.2 Million",
    rottenTomatoes: 79,
    metacritic: 67,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 2, complexity: 8, visuals: 7, emotion: 4 }
  },
  {
    id: "alien",
    title: "Alien",
    year: 1979,
    director: ["Ridley Scott"],
    cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Ian Holm"],
    genres: ["Horror", "Sci-Fi"],
    poster: "👽",
    rating: 8.5,
    runtime: 117,
    description: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission on a desolate planet.",
    awards: "Won 1 Oscar. 18 wins & 21 nominations.",
    tropes: ["Space Horror", "Haunted House in Space", "Chestburster", "Final Girl", "Corporate Greed", "Giger's Biomechanical Design", "Industrial Sci-Fi", "Slow-Burn Dread"],
    boxOffice: "$106.3 Million",
    rottenTomatoes: 93,
    metacritic: 89,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 2, complexity: 5, visuals: 9, emotion: 4 }
  },
  {
    id: "eternal-sunshine",
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    director: ["Michel Gondry"],
    cast: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo", "Elijah Wood"],
    genres: ["Romance", "Drama", "Sci-Fi"],
    poster: "🧠",
    rating: 8.3,
    runtime: 108,
    description: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
    awards: "Won 1 Oscar. 73 wins & 112 nominations.",
    tropes: ["Memory Erasure", "Non-Linear Romance", "Surrealism", "Grief of Breakup", "Fate/Coincidence", "Visual Metaphors", "Melancholy Tone", "Quirky Romance"],
    boxOffice: "$74.0 Million",
    rottenTomatoes: 92,
    metacritic: 89,
    mpaaRating: "R",
    attributes: { pacing: 6, tone: 4, complexity: 8, visuals: 8, emotion: 9 }
  },
  {
    id: "the-grand-budapest-hotel",
    title: "The Grand Budapest Hotel",
    year: 2014,
    director: ["Wes Anderson"],
    cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Saoirse Ronan", "Willem Dafoe"],
    genres: ["Comedy", "Adventure", "Crime"],
    poster: "🏨",
    rating: 8.1,
    runtime: 99,
    description: "A writer encounters the owner of a decaying high-class hotel, who relates the years he spent as a lobby boy under the distinguished concierge, Monsieur Gustave H.",
    awards: "Won 4 Oscars. 131 wins & 225 nominations.",
    tropes: ["Symmetrical Cinematography", "Pastel Aesthetic", "Deadpan Humor", "Story-Within-A-Story", "Quirky Characters", "Heist/Chase", "Nostalgia for a Bygone Era", "European Charm"],
    boxOffice: "$173.0 Million",
    rottenTomatoes: 92,
    metacritic: 88,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 7, complexity: 5, visuals: 10, emotion: 6 }
  },
  {
    id: "the-godfather",
    title: "The Godfather",
    year: 1972,
    director: ["Francis Ford Coppola"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton", "Robert Duvall"],
    genres: ["Crime", "Drama"],
    poster: "🌹",
    rating: 9.2,
    runtime: 175,
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    awards: "Won 3 Oscars. 31 wins & 30 nominations.",
    tropes: ["Mafia / Organized Crime", "Family Loyalty", "Corrupting Influence of Power", "Tragic Transition", "Epic Scale", "Betrayal", "Offer You Can't Refuse", "Cinematic Masterpiece"],
    boxOffice: "$250.4 Million",
    rottenTomatoes: 97,
    metacritic: 100,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 2, complexity: 7, visuals: 8, emotion: 7 }
  },
  {
    id: "whall-e",
    title: "WALL-E",
    year: 2008,
    director: ["Andrew Stanton"],
    cast: ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard"],
    genres: ["Animation", "Adventure", "Family", "Sci-Fi"],
    poster: "🤖",
    rating: 8.4,
    runtime: 98,
    description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    awards: "Won 1 Oscar. 92 wins & 90 nominations.",
    tropes: ["Post-Apocalyptic Earth", "Silent Romance", "Cute Robots", "Environmental Warning", "Space Cruise Ship", "Corporate Monopoly", "Pure Hearts", "Visual Storytelling"],
    boxOffice: "$533.3 Million",
    rottenTomatoes: 95,
    metacritic: 95,
    mpaaRating: "G",
    attributes: { pacing: 6, tone: 6, complexity: 4, visuals: 9, emotion: 9 }
  },
  {
    id: "gladiator",
    title: "Gladiator",
    year: 2000,
    director: ["Ridley Scott"],
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Richard Harris"],
    genres: ["Action", "Adventure", "Drama"],
    poster: "⚔️",
    rating: 8.5,
    runtime: 155,
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    awards: "Won 5 Oscars. 60 wins & 105 nominations.",
    tropes: ["Vengeance Story", "Slave to Warrior", "Corrupt Emperor", "Roman Arena / Colosseum", "Tragic Backstory", "Epic Speeches", "Are You Not Entertained", "Bittersweet Ending"],
    boxOffice: "$465.4 Million",
    rottenTomatoes: 80,
    metacritic: 67,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 3, complexity: 5, visuals: 8, emotion: 8 }
  },
  {
    id: "mean-girls",
    title: "Mean Girls",
    year: 2004,
    director: ["Mark Waters"],
    cast: ["Lindsay Lohan", "Rachel McAdams", "Tina Fey", "Amanda Seyfried", "Lacey Chabert"],
    genres: ["Comedy"],
    poster: "👗",
    rating: 7.1,
    runtime: 97,
    description: "Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.",
    awards: "7 wins & 17 nominations.",
    tropes: ["High School Hierarchies", "Queen Bee / Plastics", "Fish out of Water", "Burn Book", "Social Satire", "Infamous Quotes", "Coming of Age", "Revenge Plot"],
    boxOffice: "$130.1 Million",
    rottenTomatoes: 84,
    metacritic: 64,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 8, complexity: 2, visuals: 4, emotion: 5 }
  },
  {
    id: "black-swan",
    title: "Black Swan",
    year: 2010,
    director: ["Darren Aronofsky"],
    cast: ["Natalie Portman", "Mila Kunis", "Vincent Cassel", "Winona Ryder"],
    genres: ["Drama", "Thriller"],
    poster: "🦢",
    rating: 8.0,
    runtime: 108,
    description: "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's 'Swan Lake'.",
    awards: "Won 1 Oscar. 100 wins & 200+ nominations.",
    tropes: ["Psychological Descent", "Dancer / Performance Art", "Doppelganger / Alter Ego", "Body Horror", "Overbearing Mother", "Obsession with Perfection", "Unreliable Narrator", "Shocking Ending"],
    boxOffice: "$329.4 Million",
    rottenTomatoes: 85,
    metacritic: 79,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 2, complexity: 8, visuals: 8, emotion: 7 }
  },
  {
    id: "knives-out",
    title: "Knives Out",
    year: 2019,
    director: ["Rian Johnson"],
    cast: ["Daniel Craig", "Chris Evans", "Ana de Armas", "Jamie Lee Curtis", "Christopher Plummer"],
    genres: ["Comedy", "Crime", "Mystery", "Thriller"],
    poster: "🔪",
    rating: 7.9,
    runtime: 130,
    description: "A detective investigates the death of a patriarch of an eccentric, combative family.",
    awards: "Nominated for 1 Oscar. 52 wins & 110+ nominations.",
    tropes: ["Whodunnit / Murder Mystery", "Eccentric Detective", "Greedy/Dysfunctional Family", "Rich Patriarch", "Class Commentary", "Twists and Turns", "Southern Drawl", "Donut Hole Speech"],
    boxOffice: "$312.9 Million",
    rottenTomatoes: 97,
    metacritic: 82,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 7, complexity: 7, visuals: 6, emotion: 6 }
  },
  // ── UNDERRATED & ACCLAIMED FILMS ──────────────────────────────
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    director: ["Denis Villeneuve"],
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
    genres: ["Sci-Fi", "Drama", "Mystery"],
    poster: "🛸",
    rating: 7.9,
    runtime: 116,
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    awards: "Won 1 Oscar. 82 wins & 241 nominations.",
    tropes: ["Non-Linear Timeline", "First Contact", "Linguistic Puzzle", "Sapir-Whorf Hypothesis", "Grief Processing", "Tear-Jerker Ending", "Cerebral Plot", "Quiet Tension"],
    boxOffice: "$203.4 Million",
    rottenTomatoes: 94,
    metacritic: 81,
    mpaaRating: "PG-13",
    attributes: { pacing: 4, tone: 4, complexity: 9, visuals: 8, emotion: 9 }
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    director: ["Denis Villeneuve"],
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Jared Leto", "Sylvia Hoeks"],
    genres: ["Sci-Fi", "Drama", "Mystery", "Thriller"],
    poster: "🌧️",
    rating: 8.0,
    runtime: 164,
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    awards: "Won 2 Oscars. 96 wins & 162 nominations.",
    tropes: ["Identity Crisis", "Existential Dread", "Cyberpunk", "AI Consciousness", "Chosen One Subversion", "Atmospheric World-Building", "Philosophical Sci-Fi", "Slow-Burn Mystery"],
    boxOffice: "$259.2 Million",
    rottenTomatoes: 88,
    metacritic: 81,
    mpaaRating: "R",
    attributes: { pacing: 3, tone: 2, complexity: 8, visuals: 10, emotion: 7 }
  },
  {
    id: "the-prestige",
    title: "The Prestige",
    year: 2006,
    director: ["Christopher Nolan"],
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine", "David Bowie"],
    genres: ["Drama", "Mystery", "Thriller"],
    poster: "🎩",
    rating: 8.5,
    runtime: 130,
    description: "Two stage magicians engage in a bitter rivalry that becomes more and more dangerous and obsessive as they try to outwit each other with increasingly elaborate tricks.",
    awards: "Nominated for 2 Oscars. 9 wins & 44 nominations.",
    tropes: ["Rivalry", "Obsession with Greatness", "Plot Twist", "Non-Linear Narrative", "Magic & Illusion", "Doppelganger", "Sacrifice for Art", "Tesla Technology"],
    boxOffice: "$109.7 Million",
    rottenTomatoes: 76,
    metacritic: 66,
    mpaaRating: "PG-13",
    attributes: { pacing: 8, tone: 3, complexity: 9, visuals: 7, emotion: 7 }
  },
  {
    id: "memento",
    title: "Memento",
    year: 2000,
    director: ["Christopher Nolan"],
    cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
    genres: ["Mystery", "Thriller"],
    poster: "📸",
    rating: 8.4,
    runtime: 113,
    description: "A man with short-term memory loss attempts to track down his wife's murderer using tattoos and notes to piece together his fractured memory.",
    awards: "Nominated for 2 Oscars. 57 wins & 56 nominations.",
    tropes: ["Reverse Chronology", "Unreliable Narrator", "Memory Loss", "Revenge Plot", "Tattoo Notes", "Noir Thriller", "Puzzle Box Narrative", "Paranoia"],
    boxOffice: "$39.7 Million",
    rottenTomatoes: 93,
    metacritic: 80,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 2, complexity: 10, visuals: 6, emotion: 5 }
  },
  {
    id: "no-country-for-old-men",
    title: "No Country for Old Men",
    year: 2007,
    director: ["Joel Coen", "Ethan Coen"],
    cast: ["Javier Bardem", "Josh Brolin", "Tommy Lee Jones", "Woody Harrelson"],
    genres: ["Crime", "Drama", "Thriller"],
    poster: "💀",
    rating: 8.2,
    runtime: 122,
    description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
    awards: "Won 4 Oscars including Best Picture. 162 wins & 137 nominations.",
    tropes: ["Unstoppable Killer", "Fate vs Free Will", "Folk Tale Morality", "Desert Setting", "Coin Toss Philosophy", "Minimal Score", "Anti-Climactic Resolution", "Cormac McCarthy"],
    boxOffice: "$171.6 Million",
    rottenTomatoes: 93,
    metacritic: 92,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 1, complexity: 7, visuals: 8, emotion: 4 }
  },
  {
    id: "there-will-be-blood",
    title: "There Will Be Blood",
    year: 2007,
    director: ["Paul Thomas Anderson"],
    cast: ["Daniel Day-Lewis", "Paul Dano", "Ciarán Hinds"],
    genres: ["Drama"],
    poster: "🛢️",
    rating: 8.2,
    runtime: 158,
    description: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.",
    awards: "Won 2 Oscars. 115 wins & 129 nominations.",
    tropes: ["Obsession with Greatness", "Rags to Riches to Ruin", "Capitalism Critique", "Religious Hypocrisy", "Method Acting Masterclass", "Alienation", "American Frontier", "Mineral Exploration"],
    boxOffice: "$76.2 Million",
    rottenTomatoes: 91,
    metacritic: 92,
    mpaaRating: "R",
    attributes: { pacing: 3, tone: 1, complexity: 7, visuals: 9, emotion: 6 }
  },
  {
    id: "children-of-men",
    title: "Children of Men",
    year: 2006,
    director: ["Alfonso Cuarón"],
    cast: ["Clive Owen", "Julianne Moore", "Michael Caine", "Chiwetel Ejiofor"],
    genres: ["Sci-Fi", "Drama", "Thriller"],
    poster: "👶",
    rating: 7.9,
    runtime: 109,
    description: "In 2027, in a chaotic world in which women have somehow become infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.",
    awards: "Nominated for 3 Oscars. 50 wins & 112 nominations.",
    tropes: ["Dying Earth", "Hope vs Despair", "Long Take Cinematography", "Immigration Allegory", "Last Hope Baby", "Dystopian Society", "Guerilla Filmmaking", "Civilization Collapse"],
    boxOffice: "$70.5 Million",
    rottenTomatoes: 92,
    metacritic: 84,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 2, complexity: 6, visuals: 9, emotion: 8 }
  },
  {
    id: "the-lighthouse",
    title: "The Lighthouse",
    year: 2019,
    director: ["Robert Eggers"],
    cast: ["Willem Dafoe", "Robert Pattinson"],
    genres: ["Drama", "Fantasy", "Horror", "Mystery"],
    poster: "🏠",
    rating: 7.4,
    runtime: 109,
    description: "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
    awards: "Nominated for 1 Oscar. 60 wins & 109 nominations.",
    tropes: ["Isolation Horror", "Descent into Madness", "Mythological Allusion", "Black & White Cinematography", "Fart Jokes", "Ambiguous Supernatural", "Power Dynamics", "Nautical Folklore"],
    boxOffice: "$18.3 Million",
    rottenTomatoes: 90,
    metacritic: 83,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 1, complexity: 8, visuals: 9, emotion: 5 }
  },
  {
    id: "midsommar",
    title: "Midsommar",
    year: 2019,
    director: ["Ari Aster"],
    cast: ["Florence Pugh", "Jack Reynor", "William Jackson Harper", "Vilhelm Blomgren"],
    genres: ["Drama", "Horror", "Mystery", "Thriller"],
    poster: "🌸",
    rating: 7.1,
    runtime: 148,
    description: "A couple travels to Sweden to visit their friend's rural hometown for its fabled midsummer festival, but what begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition.",
    awards: "6 wins & 59 nominations.",
    tropes: ["Folk Horror", "Daylight Horror", "Cult", "Breakup Story", "Grief Processing", "Swedish Midsummer", "Trippy Hallucinations", "Bright & Beautiful Nightmare"],
    boxOffice: "$48.0 Million",
    rottenTomatoes: 83,
    metacritic: 72,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 2, complexity: 6, visuals: 9, emotion: 7 }
  },
  {
    id: "the-witch",
    title: "The Witch",
    year: 2015,
    director: ["Robert Eggers"],
    cast: ["Anya Taylor-Joy", "Ralph Ineson", "Kate Dickie", "Harvey Scrimshaw"],
    genres: ["Drama", "Fantasy", "Horror", "Mystery"],
    poster: "🐐",
    rating: 7.0,
    runtime: 92,
    description: "A family in 1630s New England is torn apart by the forces of witchcraft, black magic, and possession.",
    awards: "15 wins & 49 nominations.",
    tropes: ["Folk Horror", "Puritan Setting", "Period Authenticity", "Witch Trials", "Family Disintegration", "Corruption of Innocence", "Slow-Burn Dread", "Black Phillip"],
    boxOffice: "$40.4 Million",
    rottenTomatoes: 91,
    metacritic: 83,
    mpaaRating: "R",
    attributes: { pacing: 3, tone: 1, complexity: 6, visuals: 8, emotion: 6 }
  },
  {
    id: "ex-machina",
    title: "Ex Machina",
    year: 2014,
    director: ["Alex Garland"],
    cast: ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac"],
    genres: ["Sci-Fi", "Drama", "Thriller"],
    poster: "🤖",
    rating: 7.7,
    runtime: 108,
    description: "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.",
    awards: "Won 1 Oscar. 87 wins & 149 nominations.",
    tropes: ["AI Consciousness", "Turing Test", "Isolated Setting", "Manipulation & Deception", "Techno-Thriller", "Gender & Power", "Minimal Cast", "Ethical Dilemma"],
    boxOffice: "$36.9 Million",
    rottenTomatoes: 92,
    metacritic: 78,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 3, complexity: 8, visuals: 8, emotion: 5 }
  },
  {
    id: "prisoners",
    title: "Prisoners",
    year: 2013,
    director: ["Denis Villeneuve"],
    cast: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello", "Paul Dano", "Terrence Howard", "Melissa Leo"],
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    poster: "🔎",
    rating: 8.1,
    runtime: 153,
    description: "When his daughter and her friend go missing, a father takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
    awards: "Nominated for 1 Oscar. 16 wins & 59 nominations.",
    tropes: ["Descent into Darkness", "Vigilante Justice", "Moral Ambiguity", "Kidnapping Mystery", "Rainy Atmosphere", "Slow-Burn Thriller", "Family Protection", "Prisoner's Dilemma"],
    boxOffice: "$122.1 Million",
    rottenTomatoes: 81,
    metacritic: 74,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 1, complexity: 7, visuals: 7, emotion: 7 }
  },
  {
    id: "nightcrawler",
    title: "Nightcrawler",
    year: 2014,
    director: ["Dan Gilroy"],
    cast: ["Jake Gyllenhaal", "Rene Russo", "Riz Ahmed", "Bill Paxton"],
    genres: ["Crime", "Drama", "Thriller"],
    poster: "📹",
    rating: 7.9,
    runtime: 117,
    description: "When Louis Bloom, a driven man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story.",
    awards: "Nominated for 1 Oscar. 22 wins & 93 nominations.",
    tropes: ["Ambitious Sociopath", "Media Critique", "American Dream Darkside", "Character Study", "Night LA Cinematography", "Manipulation", "Dark Comedy", "Anti-Hero"],
    boxOffice: "$50.3 Million",
    rottenTomatoes: 95,
    metacritic: 76,
    mpaaRating: "R",
    attributes: { pacing: 8, tone: 2, complexity: 5, visuals: 8, emotion: 4 }
  },
  {
    id: "drive",
    title: "Drive",
    year: 2011,
    director: ["Nicolas Winding Refn"],
    cast: ["Ryan Gosling", "Carey Mulligan", "Bryan Cranston", "Albert Brooks", "Oscar Isaac"],
    genres: ["Action", "Drama", "Thriller"],
    poster: "🚗",
    rating: 7.8,
    runtime: 100,
    description: "A mysterious Hollywood stuntman and mechanic moonlights as a getaway driver and finds himself in trouble when he helps out his neighbor.",
    awards: "Won 1 Oscar (Best Sound Editing). 39 wins & 110 nominations.",
    tropes: ["Silent Protagonist", "Stylized Violence", "Neon Noir", "Synthwave Soundtrack", "Scorpion Jacket", "Anti-Hero", "LA Underworld", "Minimal Dialogue"],
    boxOffice: "$78.1 Million",
    rottenTomatoes: 93,
    metacritic: 79,
    mpaaRating: "R",
    attributes: { pacing: 6, tone: 3, complexity: 4, visuals: 9, emotion: 6 }
  },
  {
    id: "moonlight",
    title: "Moonlight",
    year: 2016,
    director: ["Barry Jenkins"],
    cast: ["Trevante Rhodes", "Ashton Sanders", "Alex Hibbert", "Mahershala Ali", "Naomie Harris", "Janelle Monáe"],
    genres: ["Drama"],
    poster: "🌙",
    rating: 7.4,
    runtime: 111,
    description: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.",
    awards: "Won 3 Oscars including Best Picture. 244 wins & 315 nominations.",
    tropes: ["Coming of Age", "Three Act Life", "Identity & Sexuality", "Color Grading Mastery", "Silent Emotion", "Miami Setting", "Drug Dealer Mentor", "Tender Masculinity"],
    boxOffice: "$65.2 Million",
    rottenTomatoes: 98,
    metacritic: 99,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 5, complexity: 6, visuals: 9, emotion: 10 }
  },
  {
    id: "the-revenant",
    title: "The Revenant",
    year: 2015,
    director: ["Alejandro González Iñárritu"],
    cast: ["Leonardo DiCaprio", "Tom Hardy", "Domhnall Gleeson", "Will Poulter"],
    genres: ["Action", "Adventure", "Drama", "Thriller"],
    poster: "🐻",
    rating: 8.0,
    runtime: 156,
    description: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
    awards: "Won 3 Oscars. 107 wins & 232 nominations.",
    tropes: ["Survival Story", "Revenge Quest", "Natural Light Filmmaking", "Bear Attack", "Wilderness Setting", "Single Take Aesthetic", "Human vs Nature", "Brutal Realism"],
    boxOffice: "$533.0 Million",
    rottenTomatoes: 78,
    metacritic: 76,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 2, complexity: 5, visuals: 10, emotion: 6 }
  },
  {
    id: "birdman",
    title: "Birdman",
    year: 2014,
    director: ["Alejandro González Iñárritu"],
    cast: ["Michael Keaton", "Edward Norton", "Emma Stone", "Naomi Watts", "Zach Galifianakis"],
    genres: ["Comedy", "Drama"],
    poster: "🦅",
    rating: 7.7,
    runtime: 119,
    description: "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.",
    awards: "Won 4 Oscars including Best Picture. 189 wins & 212 nominations.",
    tropes: ["One-Shot Illusion", "Meta-Commentary", "Ego vs Art", "Broadway Setting", "Jazz Drum Score", "Fading Celebrity", "Reality vs Fantasy", "Theater Within Film"],
    boxOffice: "$103.2 Million",
    rottenTomatoes: 91,
    metacritic: 88,
    mpaaRating: "R",
    attributes: { pacing: 9, tone: 4, complexity: 7, visuals: 9, emotion: 6 }
  },
  {
    id: "spotlight",
    title: "Spotlight",
    year: 2015,
    director: ["Tom McCarthy"],
    cast: ["Mark Ruffalo", "Michael Keaton", "Rachel McAdams", "Liev Schreiber", "John Slattery", "Stanley Tucci"],
    genres: ["Biography", "Crime", "Drama", "History"],
    poster: "📰",
    rating: 8.1,
    runtime: 129,
    description: "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.",
    awards: "Won 2 Oscars including Best Picture. 100 wins & 141 nominations.",
    tropes: ["Investigative Journalism", "Institutional Cover-Up", "Truth-Seeking Team", "Slow & Methodical", "Real Events Adaptation", "Moral Reckoning", "Underdog vs System", "Procedural"],
    boxOffice: "$98.3 Million",
    rottenTomatoes: 97,
    metacritic: 93,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 4, complexity: 6, visuals: 5, emotion: 7 }
  },
  {
    id: "manchester-by-the-sea",
    title: "Manchester by the Sea",
    year: 2016,
    director: ["Kenneth Lonergan"],
    cast: ["Casey Affleck", "Michelle Williams", "Lucas Hedges", "Kyle Chandler"],
    genres: ["Drama"],
    poster: "🌊",
    rating: 7.8,
    runtime: 137,
    description: "A depressed uncle is asked to look after his teenage nephew after the boy's father dies.",
    awards: "Won 2 Oscars. 179 wins & 255 nominations.",
    tropes: ["Grief & Loss", "Small Town Setting", "Frozen Emotions", "Flashback Trauma", "Reluctant Guardian", "Cape Cod Winter", "Quiet Devastation", "Legal Guardian"],
    boxOffice: "$79.0 Million",
    rottenTomatoes: 96,
    metacritic: 96,
    mpaaRating: "R",
    attributes: { pacing: 4, tone: 2, complexity: 5, visuals: 6, emotion: 10 }
  },
  {
    id: "marriage-story",
    title: "Marriage Story",
    year: 2019,
    director: ["Noah Baumbach"],
    cast: ["Adam Driver", "Scarlett Johansson", "Laura Dern", "Alan Alda", "Ray Liotta"],
    genres: ["Comedy", "Drama", "Romance"],
    poster: "💔",
    rating: 7.9,
    runtime: 137,
    description: "A stage director and his actor wife struggle through a grueling divorce that pushes them to their personal and creative extremes.",
    awards: "Won 1 Oscar (Laura Dern). 133 wins & 318 nominations.",
    tropes: ["Divorce Drama", "Coast to Coast Custody", "Emotional Knife Fight", "Standalone Songs", "Lawyer Archetypes", "Mutual Love & Destruction", "Theater vs Film", "Charlie's Letter"],
    boxOffice: "$313,000 (Netflix)",
    rottenTomatoes: 95,
    metacritic: 94,
    mpaaRating: "R",
    attributes: { pacing: 6, tone: 4, complexity: 5, visuals: 6, emotion: 10 }
  },
  {
    id: "sound-of-metal",
    title: "Sound of Metal",
    year: 2020,
    director: ["Darius Marder"],
    cast: ["Riz Ahmed", "Olivia Cooke", "Paul Raci", "Lauren Ridloff"],
    genres: ["Drama", "Music"],
    poster: "🥁",
    rating: 7.7,
    runtime: 120,
    description: "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
    awards: "Won 2 Oscars. 58 wins & 121 nominations.",
    tropes: ["Disability Representation", "Acceptance vs Denial", "Sound Design Masterclass", "Drummer's Nightmare", "Deaf Community", "Addiction Recovery", "Sensory Immersion", "Silent World"],
    boxOffice: "$3.3 Million",
    rottenTomatoes: 97,
    metacritic: 82,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 4, complexity: 5, visuals: 6, emotion: 9 }
  },
  {
    id: "the-father",
    title: "The Father",
    year: 2020,
    director: ["Florian Zeller"],
    cast: ["Anthony Hopkins", "Olivia Colman", "Mark Gatiss", "Olivia Williams", "Imogen Poots", "Rufus Sewell"],
    genres: ["Drama", "Mystery"],
    poster: "🧓",
    rating: 8.2,
    runtime: 97,
    description: "A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.",
    awards: "Won 2 Oscars (Best Actor, Best Adapted Screenplay). 99 wins & 193 nominations.",
    tropes: ["Dementia Portrayal", "Unreliable Reality", "Shifting Perspectives", "Apartment as Labyrinth", "Time Distortion", "Parent-Child Reversal", "Confusion Immersion", "Oscar-Worthy Acting"],
    boxOffice: "$25.4 Million",
    rottenTomatoes: 98,
    metacritic: 88,
    mpaaRating: "PG-13",
    attributes: { pacing: 5, tone: 3, complexity: 9, visuals: 6, emotion: 10 }
  },
  {
    id: "promising-young-woman",
    title: "Promising Young Woman",
    year: 2020,
    director: ["Emerald Fennell"],
    cast: ["Carey Mulligan", "Bo Burnham", "Alison Brie", "Clancy Brown", "Jennifer Coolidge"],
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    poster: "💄",
    rating: 7.5,
    runtime: 113,
    description: "A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.",
    awards: "Won 1 Oscar. 85 wins & 212 nominations.",
    tropes: ["Revenge Thriller", "Rape Culture Critique", "Pastel Aesthetic", "Subverted Expectations", "Catfish Premise", "Feminist Rage", "Candy-Colored Darkness", "Justice Questioned"],
    boxOffice: "$19.0 Million",
    rottenTomatoes: 90,
    metacritic: 73,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 3, complexity: 7, visuals: 7, emotion: 7 }
  },
  {
    id: "coda",
    title: "CODA",
    year: 2021,
    director: ["Sian Heder"],
    cast: ["Emilia Jones", "Marlee Matlin", "Troy Kotsur", "Daniel Durant", "Eugenio Derbez"],
    genres: ["Comedy", "Drama", "Music", "Romance"],
    poster: "🤟",
    rating: 8.0,
    runtime: 111,
    description: "As a CODA (Child of Deaf Adults), Ruby is the only hearing person in her family. When the family's fishing business is threatened, she finds herself torn between pursuing her love of music and her fear of abandoning her parents.",
    awards: "Won 3 Oscars including Best Picture. 83 wins & 84 nominations.",
    tropes: ["Coming of Age", "Music Dreams", "Family Obligation", "Deaf Representation", "Small Town Setting", "Romantic Interest", "Singing Competition", "Independence vs Loyalty"],
    boxOffice: "$1.1 Million (Apple TV+)",
    rottenTomatoes: 94,
    metacritic: 72,
    mpaaRating: "PG-13",
    attributes: { pacing: 6, tone: 8, complexity: 3, visuals: 5, emotion: 9 }
  },
  {
    id: "past-lives",
    title: "Past Lives",
    year: 2023,
    director: ["Celine Song"],
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    genres: ["Drama", "Romance"],
    poster: "💫",
    rating: 7.8,
    runtime: 105,
    description: "Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates from South Korea. Two decades later, they are reunited in New York for one fateful week.",
    awards: "Nominated for 2 Oscars. 134 wins & 198 nominations.",
    tropes: ["Fated Lovers", "In-Yun Philosophy", "Immigration & Identity", "Childhood Sweethearts", "Bittersweet Reunion", "24 Years Apart", "Quiet Heartbreak", "What-If Scenario"],
    boxOffice: "$25.3 Million",
    rottenTomatoes: 95,
    metacritic: 94,
    mpaaRating: "PG-13",
    attributes: { pacing: 4, tone: 5, complexity: 5, visuals: 7, emotion: 10 }
  },
  {
    id: "the-holdovers",
    title: "The Holdovers",
    year: 2023,
    director: ["Alexander Payne"],
    cast: ["Paul Giamatti", "Da'Vine Joy Randolph", "Dominic Sessa"],
    genres: ["Comedy", "Drama"],
    poster: "🎄",
    rating: 7.9,
    runtime: 133,
    description: "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit students who have no place to go.",
    awards: "Won 1 Oscar (Da'Vine Joy Randolph). 89 wins & 149 nominations.",
    tropes: ["Unlikely Bonds", "Christmas Setting", "Found Family", "Grumpy Mentor", "70s Aesthetic", "Class Divide", "Healing Together", "Academic Prison"],
    boxOffice: "$41.2 Million",
    rottenTomatoes: 93,
    metacritic: 82,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 6, complexity: 4, visuals: 6, emotion: 8 }
  },
  {
    id: "anatomy-of-a-fall",
    title: "Anatomy of a Fall",
    year: 2023,
    director: ["Justine Triet"],
    cast: ["Sandra Hüller", "Swann Arlaud", "Milo Machado Graner", "Antoine Reinartz"],
    genres: ["Drama", "Mystery", "Thriller"],
    poster: "⚖️",
    rating: 7.8,
    runtime: 152,
    description: "A woman is suspected of her husband's murder, and their blind son faces a moral dilemma as the sole witness.",
    awards: "Won 1 Oscar (Best Original Screenplay). 146 wins & 261 nominations.",
    tropes: ["Courtroom Drama", "Marriage Deconstruction", "Blind Witness", "Ambiguous Truth", "Language Barrier", "European Art Cinema", "Relationship Scrutiny", "Who's Lying"],
    boxOffice: "$35.1 Million",
    rottenTomatoes: 96,
    metacritic: 87,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 3, complexity: 8, visuals: 6, emotion: 7 }
  },
  {
    id: "poor-things",
    title: "Poor Things",
    year: 2023,
    director: ["Yorgos Lanthimos"],
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef"],
    genres: ["Comedy", "Drama", "Fantasy", "Romance", "Sci-Fi"],
    poster: "🧠",
    rating: 8.0,
    runtime: 141,
    description: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    awards: "Won 4 Oscars. 174 wins & 311 nominations.",
    tropes: ["Frankenstein Retelling", "Female Liberation", "Surreal World-Building", "Fish-Eye Lenses", "Steampunk Aesthetic", "Body Autonomy", "Childlike Discovery", "Lanthimos Absurdism"],
    boxOffice: "$117.6 Million",
    rottenTomatoes: 92,
    metacritic: 87,
    mpaaRating: "R",
    attributes: { pacing: 7, tone: 7, complexity: 6, visuals: 10, emotion: 6 }
  },
  {
    id: "the-zone-of-interest",
    title: "The Zone of Interest",
    year: 2023,
    director: ["Jonathan Glazer"],
    cast: ["Christian Friedel", "Sandra Hüller"],
    genres: ["Drama", "History", "War"],
    poster: "🏡",
    rating: 7.4,
    runtime: 105,
    description: "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
    awards: "Won 2 Oscars. 145 wins & 203 nominations.",
    tropes: ["Holocaust from Afar", "Domestic Horror", "Sound Design as Witness", "Garden & Smokestacks", "Banality of Evil", "Clinical Observation", "No Shown Violence", "Complicity"],
    boxOffice: "$24.4 Million",
    rottenTomatoes: 93,
    metacritic: 85,
    mpaaRating: "PG-13",
    attributes: { pacing: 3, tone: 1, complexity: 7, visuals: 8, emotion: 8 }
  },
  {
    id: "killers-of-the-flower-moon",
    title: "Killers of the Flower Moon",
    year: 2023,
    director: ["Martin Scorsese"],
    cast: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone", "Jesse Plemons"],
    genres: ["Crime", "Drama", "History", "Mystery", "Thriller"],
    poster: "🌺",
    rating: 7.8,
    runtime: 206,
    description: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one. As the death toll rises, the newly created FBI desperately tries to unravel the mystery.",
    awards: "Nominated for 10 Oscars. 60+ wins & 190 nominations.",
    tropes: ["True Crime Epic", "Osage Murders", "Systemic Racism", "Betrayal & Greed", "Scorsese De-Aging", "Western Noir", "Slow-Burn Justice", "Indigenous Tragedy"],
    boxOffice: "$157.0 Million",
    rottenTomatoes: 93,
    metacritic: 82,
    mpaaRating: "R",
    attributes: { pacing: 3, tone: 2, complexity: 7, visuals: 8, emotion: 7 }
  },
  {
    id: "the-banshees-of-inisherin",
    title: "The Banshees of Inisherin",
    year: 2022,
    director: ["Martin McDonagh"],
    cast: ["Colin Farrell", "Brendan Gleeson", "Kerry Condon", "Barry Keoghan"],
    genres: ["Comedy", "Drama"],
    poster: "🎻",
    rating: 7.7,
    runtime: 114,
    description: "Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.",
    awards: "Nominated for 9 Oscars. 111 wins & 302 nominations.",
    tropes: ["Friendship Breakup", "Irish Island Setting", "Donkey Companion", "Self-Harm Allegory", "Civil War Backdrop", "Dark Comedy", "Existential Isolation", "Stubborn Pride"],
    boxOffice: "$49.2 Million",
    rottenTomatoes: 96,
    metacritic: 87,
    mpaaRating: "R",
    attributes: { pacing: 5, tone: 4, complexity: 6, visuals: 8, emotion: 7 }
  },
  {
    id: "aftersun",
    title: "Aftersun",
    year: 2022,
    director: ["Charlotte Wells"],
    cast: ["Paul Mescal", "Frankie Corio"],
    genres: ["Drama"],
    poster: "☀️",
    rating: 7.7,
    runtime: 102,
    description: "Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between as she tries to reconcile the father she knew with the man she didn't.",
    awards: "Nominated for 1 Oscar (Paul Mescal). 103 wins & 153 nominations.",
    tropes: ["Memory & Nostalgia", "Father-Daughter Bond", "DV Cam Aesthetic", "Unspoken Grief", "Holiday Setting", "Dual Timelines", "Emotional Ambiguity", "Indie Breakout"],
    boxOffice: "$9.5 Million",
    rottenTomatoes: 96,
    metacritic: 95,
    mpaaRating: "R",
    attributes: { pacing: 3, tone: 5, complexity: 6, visuals: 7, emotion: 10 }
  },
  {
    id: "tenet",
    title: "Tenet",
    year: 2020,
    director: ["Christopher Nolan"],
    cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki", "Kenneth Branagh"],
    genres: ["Action", "Sci-Fi", "Thriller"],
    poster: "⏱️",
    rating: 7.3,
    runtime: 150,
    description: "Armed with only the word 'Tenet,' and fighting for the survival of the entire world, a protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    awards: "Won 1 Oscar. 31 wins & 63 nominations.",
    tropes: ["Time Inversion", "Temporal Pincer", "Mind-Bending Action", "Nolan Puzzle Box", "Spy Thriller", "Entropy Reversal", "Palindromic Plot", "Cool Under Pressure"],
    boxOffice: "$365.3 Million",
    rottenTomatoes: 69,
    metacritic: 69,
    mpaaRating: "PG-13",
    attributes: { pacing: 9, tone: 3, complexity: 10, visuals: 9, emotion: 3 }
  },
  {
    id: "dunkirk",
    title: "Dunkirk",
    year: 2017,
    director: ["Christopher Nolan"],
    cast: ["Fionn Whitehead", "Tom Hardy", "Mark Rylance", "Harry Styles", "Kenneth Branagh", "Cillian Murphy"],
    genres: ["Action", "Drama", "History", "Thriller", "War"],
    poster: "⛵",
    rating: 7.8,
    runtime: 106,
    description: "Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.",
    awards: "Won 3 Oscars. 92 wins & 147 nominations.",
    tropes: ["Triptych Timeline", "Minimal Dialogue", "War Survival", "Hans Zimmer Ticking", "Dunkirk Spirit", "Practical Effects", "Christopher Nolan Structure", "Land Sea Air"],
    boxOffice: "$527.3 Million",
    rottenTomatoes: 92,
    metacritic: 94,
    mpaaRating: "PG-13",
    attributes: { pacing: 9, tone: 3, complexity: 7, visuals: 10, emotion: 6 }
  },
  {
    id: "1917",
    title: "1917",
    year: 2019,
    director: ["Sam Mendes"],
    cast: ["George MacKay", "Dean-Charles Chapman", "Mark Strong", "Andrew Scott", "Benedict Cumberbatch", "Colin Firth"],
    genres: ["Action", "Drama", "Thriller", "War"],
    poster: "⚔️",
    rating: 8.2,
    runtime: 119,
    description: "Two young British soldiers during World War I are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldiers' brothers, from walking straight into a deadly trap.",
    awards: "Won 3 Oscars. 103 wins & 208 nominations.",
    tropes: ["One-Shot Illusion", "Race Against Time", "Trench Warfare", "Roger Deakins Cinematography", "Linear Journey", "War Is Hell", "Personal Mission", "1600 Lives"],
    boxOffice: "$384.9 Million",
    rottenTomatoes: 88,
    metacritic: 78,
    mpaaRating: "R",
    attributes: { pacing: 9, tone: 2, complexity: 4, visuals: 10, emotion: 8 }
  },
];

export const GENRES = [
  "Action", "Adventure", "Animation", "Biography", "Comedy", 
  "Crime", "Drama", "Family", "Fantasy", "History", 
  "Horror", "Music", "Mystery", "Romance", "Sci-Fi", "Thriller"
];

export const COMMON_TROPES = [
  "Time Travel", "Mind-bending", "Heist", "Unreliable Narrator", "Plot Twist",
  "Post-Apocalyptic", "Dystopian Society", "Musical Numbers", "Bittersweet Ending",
  "Tear-Jerker Ending", "Star-Crossed Lovers", "Abusive Mentor", "Obsession with Greatness",
  "Multiverse", "Generational Trauma", "Absurdist Humor", "Martial Arts", "Class Struggle",
  "Slow-Burn Dread", "Jumpscare Free (Mostly)", "Mind Control", "Hypnosis", "First Love",
  "Retired Badass", "One-Man Army", "Coming of Age", "Prison Life", "Unjust Conviction",
  "Voiceover Narration", "Witty Dialogue", "Stylized Violence", "Ensemble Cast",
  "Bullet Time", "Cyberpunk", "Asylum/Mental Hospital", "Haunted Hotel", "Ghibli Magic",
  "Comic Book Aesthetic", "Meta-Humor", "Feminist Commentary", "Historical Biopic",
  "Epic High Fantasy", "The Quest", "Serial Killer", "Body Horror", "Whodunnit", "Mafia",
  "Non-Linear Timeline", "First Contact", "Linguistic Puzzle", "Identity Crisis",
  "Rivalry", "Reverse Chronology", "Memory Loss", "Unstoppable Killer", "Fate vs Free Will",
  "Descent into Madness", "Isolation Horror", "Folk Horror", "Cult", "AI Consciousness",
  "Turing Test", "Survival Story", "Revenge Quest", "One-Shot Illusion",
  "Investigative Journalism", "Grief & Loss", "Divorce Drama", "Disability Representation",
  "Dementia Portrayal", "Revenge Thriller", "Courtroom Drama", "True Crime Epic",
  "Friendship Breakup", "Memory & Nostalgia", "Time Inversion", "War Survival"
];

export const POPULAR_PEOPLE = {
  directors: [
    "Christopher Nolan", "Damien Chazelle", "Denis Villeneuve", "George Miller",
    "Bong Joon Ho", "Ari Aster", "Jordan Peele", "Quentin Tarantino",
    "Martin Scorsese", "Stanley Kubrick", "Hayao Miyazaki", "Greta Gerwig",
    "David Fincher", "Ridley Scott", "Michel Gondry", "Wes Anderson",
    "Francis Ford Coppola", "Rian Johnson", "Paul Thomas Anderson",
    "Joel Coen", "Ethan Coen", "Alfonso Cuarón", "Robert Eggers",
    "Alex Garland", "Nicolas Winding Refn", "Barry Jenkins",
    "Alejandro González Iñárritu", "Kenneth Lonergan", "Noah Baumbach",
    "Emerald Fennell", "Yorgos Lanthimos", "Jonathan Glazer",
    "Martin McDonagh", "Charlotte Wells", "Sam Mendes", "Alexander Payne",
    "Justine Triet", "Darius Marder", "Tom McCarthy", "Dan Gilroy",
    "Sian Heder", "Celine Song", "Florian Zeller"
  ],
  actors: [
    "Matthew McConaughey", "Anne Hathaway", "Leonardo DiCaprio", "Tom Hardy",
    "Christian Bale", "Timothée Chalamet", "Zendaya", "Charlize Theron",
    "Ryan Gosling", "Emma Stone", "Miles Teller", "J.K. Simmons",
    "Michelle Yeoh", "Ke Huy Quan", "Daniel Kaluuya", "Rachel McAdams",
    "Keanu Reeves", "Morgan Freeman", "Brad Pitt", "Samuel L. Jackson",
    "Jack Nicholson", "Tom Hanks", "Margot Robbie", "Cillian Murphy",
    "Robert Downey Jr.", "Elijah Wood", "Ian McKellen", "Viggo Mortensen",
    "Sigourney Weaver", "Kate Winslet", "Ralph Fiennes", "Al Pacino",
    "Joaquin Phoenix", "Natalie Portman", "Daniel Craig", "Chris Evans",
    "Amy Adams", "Jeremy Renner", "Harrison Ford", "Ana de Armas",
    "Hugh Jackman", "Scarlett Johansson", "Michael Caine", "Guy Pearce",
    "Carrie-Anne Moss", "Javier Bardem", "Josh Brolin", "Tommy Lee Jones",
    "Daniel Day-Lewis", "Paul Dano", "Clive Owen", "Julianne Moore",
    "Willem Dafoe", "Robert Pattinson", "Florence Pugh", "Anya Taylor-Jour",
    "Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac", "Jake Gyllenhaal",
    "Carey Mulligan", "Bryan Cranston", "Riz Ahmed", "Casey Affleck",
    "Michelle Williams", "Adam Driver", "Olivia Cooke", "Paul Raci",
    "Anthony Hopkins", "Olivia Colman", "Mark Ruffalo", "Michael Keaton",
    "Emma Stone", "Colin Farrell", "Brendan Gleeson", "Paul Mescal",
    "John David Washington", "Fionn Whitehead", "Mark Rylance",
    "George MacKay", "Dean-Charles Chapman", "Lily Gladstone",
    "Sandra Hüller", "Mark Strong", "Andrew Scott", "Benedict Cumberbatch"
  ]
};
